"""record which provider produced each embedding

Mock embeddings and Gemini embeddings occupy different vector spaces. Cosine
similarity between one of each is meaningless noise — not "low similarity",
but no signal at all.

That matters because `FallbackProvider` exists precisely to degrade a failed
Gemini call to the mock provider mid-request. Without this column, a demo
running on Gemini that hit one transient 503 would store one mock vector
among Gemini ones, and that complaint could never merge with its own
duplicates. Clustering would look broken for a reason nobody could see.

With the origin recorded, `find_similar_complaints` compares like with like:
a mixed dataset degrades into visibly separate clusters (obvious, and
explainable) instead of silently losing matches.

Existing rows are backfilled as 'mock', which is what they are: everything
seeded before this migration was generated by MockProvider.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-09
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str]] = None
depends_on: Union[str, Sequence[str]] = None


def upgrade() -> None:
    op.add_column(
        "complaint_embeddings",
        sa.Column(
            "provider",
            sa.String(64),
            nullable=False,
            server_default="mock",
        ),
    )
    # Similarity search always filters on this, so it belongs in the index
    # that supports the lookup.
    op.create_index(
        "ix_complaint_embeddings_provider", "complaint_embeddings", ["provider"]
    )


def downgrade() -> None:
    op.drop_index("ix_complaint_embeddings_provider", table_name="complaint_embeddings")
    op.drop_column("complaint_embeddings", "provider")
